### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'drivername'

### ISSUE THREAD

**Issue by sr1919** [pxsocs/cryptoblotter#16]
I'm facing the following issue after trying to login (via demo@ account).
It happened in v0.02 when I installed a few days ago and seems the same after upgrade to v0.03.

Traceback (most recent call last):
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry[key]
KeyError: 123145565372416

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/serhiys/dev/cryptoblotter/cryptoalpha/users/routes.py", line 38, in login
    user = User.query.filter_by(email=form.email.data).first()
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1012, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3213, in __call__
    return self.class_(**local_kw)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 143, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 877, in engine
    return self.get_engine()
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 556, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "/Users/serhiys/dev/cryptoblotter/cb_env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 830, in apply_driver_hacks
    if info.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'

**Comment by pxsocs** [comment]
Cannot duplicate on my side. Can you try the following steps:

__1) Make sure the sql environment variable is set__
    Type the following at the command line:
        Mac:
        `export SQLALCHEMY_DATABASE_URI=sqlite:///alpha.db`
        Windows: 
        `SET SQLALCHEMY_DATABASE_URI=sqlite:///alpha.db`

__2) If the above didn't fix the issue, please copy and paste here the last 20 lines of `debug.log` file located at your home cb folder.__

**Comment by sr1919** [comment]
1) solved that. SQLALCHEMY... was missing
Thank you!
